[project]
name = "kelp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "blake3>=1.0.4",
    "cbor2>=5.6.5",
    "nlohmann-json>=3.11.3",
    "numpy>=2.2.4",
    "psutil>=7.0.0",
    "scipy>=1.15.2",
    "zstandard>=0.23.0",
]
